

CREATE TABLE `user_credential` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LAST_LOGIN_AT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

CREATE TABLE `user_information` (
  `USER_INFORMATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `ADDRESS1` varchar(100) DEFAULT NULL,
  `ADDRESS2` varchar(100) DEFAULT NULL,
  `CITY` varchar(20) NOT NULL,
  `ZIP` int(11) NOT NULL,
  PRIMARY KEY (`USER_INFORMATION_ID`),
  KEY `userid` (`USER_ID`),
  CONSTRAINT `userid` FOREIGN KEY (`USER_ID`) REFERENCES `user_credential` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `user_profile` (
  `USER_PROFILE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) NOT NULL,
  `PUBLIC_ACCESS` tinyint(1) DEFAULT '1',
  `FRIENDS_ONLY` tinyint(1) DEFAULT '0',
  `FRIENDS_OF_FRIENDS` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`USER_PROFILE_ID`),
  KEY `USER_ID_FK1` (`USER_ID`),
  CONSTRAINT `USER_ID_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `user_credential` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE `friends` (
  `REL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_PROFILE_ID` bigint(20) NOT NULL,
  `FRIEND_USER_PROFILE_ID` bigint(20) NOT NULL,
  `ADDED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ACTIVE` binary(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`REL_ID`),
  KEY `USER_PROFILE_ID` (`USER_PROFILE_ID`),
  KEY `FRIEND_USER_PROFILE_ID_FK` (`FRIEND_USER_PROFILE_ID`),
  CONSTRAINT `USER_PROFILE_ID` FOREIGN KEY (`USER_PROFILE_ID`) REFERENCES `user_profile` (`USER_PROFILE_ID`),
  CONSTRAINT `FRIEND_USER_PROFILE_ID_FK` FOREIGN KEY (`FRIEND_USER_PROFILE_ID`) REFERENCES `user_profile` (`USER_PROFILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `wall_posts` (
  `POST_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `POST_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `POST_MSG` varchar(255) NOT NULL,
  `WALL_USER_INFO_ID` bigint(20) NOT NULL,
  `POST_USER_INFO_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`POST_ID`),
  KEY `WALL_USER_ID_FK` (`WALL_USER_INFO_ID`),
  KEY `POST_USER_ID_FK` (`POST_USER_INFO_ID`),
  CONSTRAINT `WALL_USER_ID_FK` FOREIGN KEY (`WALL_USER_INFO_ID`) REFERENCES `user_information` (`USER_INFORMATION_ID`),
  CONSTRAINT `POST_USER_ID_FK` FOREIGN KEY (`POST_USER_INFO_ID`) REFERENCES `user_information` (`USER_INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `private_messages` (
  `MESSAGE_ID` bigint(20) NOT NULL,
  `FROM_USER_INFO_ID` bigint(20) NOT NULL,
  `TO_USER_INFO_ID` bigint(20) NOT NULL,
  `MESSAGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MESSAGE_BODY` varchar(255) NOT NULL,
  PRIMARY KEY (`MESSAGE_ID`),
  KEY `FROM_USER_ID_FK` (`FROM_USER_INFO_ID`),
  KEY `TO_USER_ID_FK` (`TO_USER_INFO_ID`),
  CONSTRAINT `FROM_USER_ID_FK` FOREIGN KEY (`FROM_USER_INFO_ID`) REFERENCES `user_information` (`USER_INFORMATION_ID`),
  CONSTRAINT `TO_USER_ID_FK` FOREIGN KEY (`TO_USER_INFO_ID`) REFERENCES `user_information` (`USER_INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

